name: heist
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_transformer_page_view: ^1.1.0
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  dio: ^4.0.4
  equatable: ^2.0.3
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_beacon: ^0.5.1
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_platform_widgets: ^1.12.1
  flutter_screenutil: ^5.1.1
  flutter_secure_storage: ^5.0.2
  geolocator: ^8.0.5
  google_fonts: ^2.2.0
  google_maps_flutter: ^2.1.1
  image_picker: ^0.8.4+5
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  keyboard_actions: ^3.4.6
  mask_text_input_formatter: ^2.1.0
  meta: ^1.7.0
  onesignal_flutter: ^3.2.8
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  rxdart: ^0.27.3
  transparent_image: ^2.0.0
  url_launcher: ^6.0.18

dev_dependencies:
  bloc_test: ^9.0.2
  faker: ^2.0.0
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.2
  integration_test:
    sdk: flutter
  jaguar_jwt: ^3.0.0
  mocktail: ^0.2.0
  network_image_mock: ^2.0.1
  test: ^1.17.12

flutter_icons:
  image_path_android: 'assets/icons/icon_android.png'
  image_path_ios: 'assets/icons/icon_ios.png'
  android: true
  ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: 'assets/icons/icon_android.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
