name: heist
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_transformer_page_view: ^1.0.0
  cached_network_image: ^3.0.0
  collection: ^1.15.0
  dio: ^4.0.0
  equatable: ^2.0.2
  flare_flutter: ^3.0.0
  flutter_beacon: ^0.5.0
  flutter_bloc: ^7.0.0
  flutter_cache_manager: ^3.0.2
  flutter_platform_widgets: ^1.9.0
  flutter_secure_storage: ^4.2.0
  flutter_typeahead: ^3.1.3
  geolocator: ^7.0.3
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.6
  image_picker: ^0.7.5+3
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  keyboard_actions: ^3.4.0
  mask_text_input_formatter: ^2.0.0
  meta: ^1.3.0
  onesignal_flutter: ^3.0.0
  permission_handler: ^8.1.1
  rxdart: ^0.27.0
  transparent_image: ^2.0.0
  url_launcher: ^6.0.4

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^8.0.2
  faker: ^2.0.0
  http_mock_adapter: ^0.2.1
  jaguar_jwt: ^3.0.0
  mocktail: ^0.1.1
  network_image_mock: ^2.0.0
  test: ^1.16.5

flutter:
  uses-material-design: true

  assets:
    - assets/
